using DSALGO.Algorithm.DynamicProgramming;
using DSALGO.Algorithm.GraphTheory.CycleAndSCC;
using DSALGO.DataStructure.GraphStructure;
using System.Reflection.Metadata.Ecma335;
using static DSALGO.Utility;
//int[] P = new int[] { 4, 10, 3, 12, 20, 7 };
int[] P = new int[] { 30,35,15,5,10,20,25 };
MatrixChain chain = new();
Console.WriteLine(chain.MinOperateCount(P));
chain.PrintTable();
